[general]
update_delay = 1 # Delay between rigctld queries in seconds
print_rig_data = false # Wether to print resulting frequency and mode or not

[wavelog]
host = "http://192.168.1.1" # Host of wavelog instance (with http(s)://)
radio_name = "MyRadio" # Radio name in Wavelog -> Harware Interfaces -> Radio
api_keys = ["wl...", "wl..."] # List of API keys for all users that should have the frequency updated.
                                      # All users need to have the radio configured with the same name
keepalive_seconds = 60 # While the radio is on, a packet will be sent to wavelog every x seconds even if frequency
                       # or mode hasn't changed to make sure wavelog knows the radio is still on.
                       # Make sure this is lower than the setting in wavelog under Admin -> Global Options -> Radios -> Timeout

[rigctld]
host = "192.168.1.1" # Host of rigctld instance
port = 4532 # Port of rigctld instance
allow_offline = false # Allow the rig to be turned off (script will wait until it's back on)
boot_time = 5 # Time to wait if it has been detected that rig is on, to avoid weird responses
